{% set version = "5.8" %}

package:
  name: dsdp
  version: {{ version }}

source:
  fn: DSDP{{ version }}.tar.gz
  url: http://www.mcs.anl.gov/hs/software/DSDP/DSDP{{ version }}.tar.gz
  sha256: 26aa624525a636de272c0b329e2dfd01a0d5b7827f1c1c76f393d71e37dead70
  patches: dsdp_patch.diff

build:
  skip: true  # [win and vc<14]
  number: 1203

requirements:
  build:
    - cmake
    - {{ compiler("c") }}
    - make
  host:
    - libblas
    - libcblas
    - liblapack

test:
  source_files:
    - bin/control1.dat-s
    - bin/mcp100.dat-s
    - bin/truss1.dat-s
  commands:
    - dsdp5 bin/control1.dat-s   # [not win]
    - dsdp5 bin/mcp100.dat-s   # [not win]
    - dsdp5 bin/truss1.dat-s   # [not win]
    - if not exist %LIBRARY_PREFIX%\\lib\\dsdp.lib exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\dsdp.dll exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\dsdp5.h exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\dsdpbasictypes.h exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\dsdplapack.h exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\dsdpmem.h exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\dsdpsys.h exit 1    # [win]


about:
  home: http://www.mcs.anl.gov/hs/software/DSDP/index.html
  license: DSDP
  license_file: dsdp-license
  summary: Software for semidefinite programming

extra:
  recipe-maintainers:
    - martinandersen
